import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "@repo/ui/global.css";
import LenisReact from "../../../packages/ui/src/components/wrapper/Lenis";

const roboto = Roboto({
  weight: ["100", "300", "400", "700", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <LenisReact>{children}</LenisReact>
      </body>
    </html>
  );
}
